version: '3.3'
services:
  jaegeradry:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"


    environment:
      COLLECTOR_OTLP_ENABLED: true
      LOG_LEVEL: debug

