version: '3.8'
services:
  # Servicio de base de datos MySQL
  mysqldb:
    container_name: MYSQL
    image: mysql:latest
    # Puertos expuestos del contenedor (host:container)
    ports:
      - 3306:3306

    # Variables de entorno para configurar la base de datos MySQL
    environment:
      MYSQL_DATABASE: dockersd
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: hellofriend

    # Red a la que está conectado el contenedor
    networks:
      - netadrian

  # Servicio de rastreo Jaeger
  jaeger:
    container_name: JAEGER-ADRY
    image: jaegertracing/all-in-one:latest
    # Puertos expuestos del contenedor (host:container)
    ports:
      - 16686:16686
      - 14268:14268

    # Red a la que está conectado el contenedor
    networks:
      - netadrian

  # Servicio de la aplicación Spring Boot
  springboot:
    container_name: SPRING-ADRIAN
    # Dependencias: Este servicio depende de mysqldb, lo que significa que el contenedor de MySQL debe estar en ejecución antes de iniciar este servicio.
    depends_on:
      - mysqldb
    # Imagen: Se utilizará la imagen adrianc47/spring-adry:latest, que   contenga una aplicación Spring Boot.
    image: adrianc47/spring-adry:latest
    # Construcción: El proyecto se construirá en el contexto actual usando el Dockerfile presente en la raíz del proyecto.
    build: .

    # Enlaces: Se enlaza el contenedor de jaeger para que este servicio pueda comunicarse con el servicio de Jaeger.
    links:
      - jaeger
    # Puertos expuestos del contenedor (host:container)
    ports:
      - 8080:8080
    # Variables de entorno para configurar la aplicación Spring Boot
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/dockersd
      - DATABASE_USERNAME=docker
      - DATABASE_PASSWORD=docker
      - JAEGER_HOST=jaeger

    # Red a la que está conectado el contenedor
    networks:
      - netadrian

# Definición de la red personalizada para conectar los servicios
networks:
  netadrian:
    driver: bridge
