apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/servicefordocker-netadrian: "true"
        io.kompose.service: mysqldb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: dockersd
            - name: MYSQL_PASSWORD
              value: docker
            - name: MYSQL_ROOT_PASSWORD
              value: hellofriend
            - name: MYSQL_USER
              value: docker
          image: mysql:latest
          name: mysql
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
